---
- name: Apply nodeset template
  shell: |
    kustomize build {{ dt_path }}/examples/dt/perfscale/scalelab/edpm/nodeset/. | tee nodeset.yml | oc apply -f -

- name: wait for nodeset
  shell: |
    oc wait osdpns openstack-edpm -n openstack --for condition=SetupReady --timeout=600s

- name: Apply deployment template
  shell: |
    kustomize build {{ dt_path }}/examples/dt/perfscale/scalelab/edpm/deployment/. | tee deployment.yml | oc apply -f -
