- hosts: localhost
  gather_facts: false
  #environment: "{{ ocp_environment }}"
  roles:
    - bootstrap
    - values-prep
    - values-prep-dp
    - lvms
    - common-osp
    - controlplane
    - dataplane
