---
- name: get woker node names
  shell: oc get nodes -o jsonpath='{.items[*].metadata.name}'
  register: node_names

- name: set node facts (node_*)
  set_fact:
    "{{ item_name }}": "{{ item }}"
  loop: "{{ node_names.stdout.split() }}"
  loop_control:
    index_var: node_index
  vars:
    item_name: "node_{{ node_index }}"

- name: get the first node macs (2,3 and 4th macs)
  set_fact:
    macs: "{{ ocp_inventry.json.nodes[1].mac[1:4] }}"

- name: get the ip of the first node
  command: >
    oc get nodes -o jsonpath="{range .items[*]}{.status.addresses[?(@.type=='InternalIP')].address}{'\n'}{end}"
  register:
    nodes_ip

- name: set node ip fact
  set_fact:
    "{{ item_name }}": "{{ item }}"
  loop: "{{ nodes_ip.stdout.split() }}"
  loop_control:
    index_var: node_index
  vars:
    item_name: "node_{{ node_index }}_ip" 

- name: fix and setup ssh
  include_tasks: setup-ssh.yml
  loop: "{{ range(0, 3) | list }}"

- name: get the interface names
  include_tasks: get_iface.yml
  loop: "{{ macs | zip(range(macs | length)) | map('list') | list }}"
  loop_control:
    loop_var: item

- name: get the common disk accros nodes
  include_tasks: find-node-disks.yml

- name: Render nncp.yaml
  template:
    src: nncp_values.yaml.j2
    dest: "{{ dt_path }}/examples/dt/perfscale/scalelab/nncp/values.yaml"

- name: Render service_values.yaml 
  template:
    src: service_values.yaml.j2
    dest: "{{ dt_path }}/examples/dt/perfscale/scalelab/service-values.yaml"

- name: Render lvms value
  template:
    src: lvms-values.yaml.j2
    dest: "{{ dt_path }}/examples/dt/perfscale/scalelab/lvms/values.yaml"
