---
- name: remove bad known_host entry if any
  shell:
    ssh-keygen -R {{ lookup('vars', 'node_' ~ item ~ '_ip') }}
  ignore_errors: yes

- name: Add node to known hosts
  shell: ssh-keyscan -H {{ lookup('vars', 'node_' ~ item ~ '_ip') }} >> ~/.ssh/known_hosts
  ignore_errors: yes
